// reviung keymap by @millaizha 

#include QMK_KEYBOARD_H

// layers
#define _LAYER0 0
#define _LAYER1 1
#define _LAYER2 2
#define _LAYER3 3
#define _LAYER4 4
#define _LAYER5 5

enum custom_keycodes {
    LAYER0 = SAFE_RANGE,
    LAYER1,
    LAYER2,
    LAYER3,
    LAYER4,
    LAYER5,
};


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

[_LAYER0] = LAYOUT_reviung34(KC_Q, KC_W, KC_F, KC_P, KC_B, KC_J, KC_L, KC_U, KC_Y, KC_QUOT, LGUI_T(KC_A), LALT_T(KC_R), LCTL_T(KC_S), LSFT_T(KC_T), KC_G, KC_M, RSFT_T(KC_N), RCTL_T(KC_E), RALT_T(KC_I), RGUI_T(KC_O), KC_Z, KC_X, KC_C, KC_D, KC_V, KC_K, KC_H, KC_COMM, KC_DOT, KC_SLSH, LT(1,KC_BSPC), KC_TAB, KC_ENT, LT(2,KC_SPC)),

[_LAYER1] = LAYOUT_reviung34(KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, KC_GRV, KC_SCLN, KC_RSFT, KC_RCTL, KC_RALT, KC_RGUI, KC_BSLS, KC_LBRC, KC_LCBR, KC_MINS, KC_EQL, KC_PLUS, KC_UNDS, KC_RCBR, KC_RBRC, KC_PIPE, KC_TRNS, KC_NO, KC_COMM, LT(4,KC_DOT)),

[_LAYER2] = LAYOUT_reviung34(KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, KC_F11, KC_F12, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_ESC, TO(3), KC_VOLD, KC_VOLU, KC_MUTE, KC_CAPS, KC_HOME, KC_PGDN, KC_PGUP, KC_END, LT(4,KC_DEL), KC_INS, KC_NO, KC_TRNS),

[_LAYER3] = LAYOUT_reviung34(KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_QUOT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, LT(5,KC_BSPC), KC_TAB, KC_ENT, LT(2,KC_SPC)),

[_LAYER4] = LAYOUT_reviung34(RGB_M_P, RGB_M_B, RGB_M_R, RGB_M_G, RGB_M_SW, KC_BTN3, KC_BTN1, KC_BTN2, KC_BTN4, KC_BTN5, RGB_TOG, KC_MPRV, KC_MPLY, KC_MNXT, RGB_MOD, KC_BRIU, KC_MS_L, KC_MS_D, KC_MS_U, KC_MS_R, RGB_SPD, RGB_SPI, RGB_VAD, RGB_VAI, RGB_RMOD, KC_BRID, KC_WH_L, KC_WH_D, KC_WH_U, KC_WH_R, KC_TRNS, KC_NO, KC_NO, KC_TRNS),

[_LAYER5] = LAYOUT_reviung34(KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, KC_F11, KC_F12, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_ESC, TO(0), KC_VOLD, KC_MUTE, KC_VOLU, KC_CAPS, KC_HOME, KC_PGDN, KC_PGUP, KC_END, KC_DEL, KC_INS, KC_NO, KC_TRNS) 

};

#ifdef OLED_ENABLE

oled_rotation_t oled_init_user(oled_rotation_t rotation){
    return OLED_ROTATION_180;
}

bool oled_task_user(){
    oled_set_cursor(0,1);
    
    oled_write("Hello, Mill", false);
    return false;
}

#endif